name: "Setup Go Environment"
description: "Sets up Go with caching and downloads dependencies"
inputs:
  go-version:
    description: "Go version to install"
    required: false
    default: "1.24"
  cache-dependency-path:
    description: "Path to go.sum for cache key"
    required: false
    default: "**/go.sum"

runs:
  using: "composite"
  steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.go-version }}

    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles(inputs.cache-dependency-path) }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Download dependencies
      shell: bash
      run: go mod download
