name: Build and Test

on:
  workflow_call:
    inputs:
      go-version:
        description: "Go version to use"
        required: false
        type: string
        default: "1.24"
      run-tests:
        description: "Whether to run tests"
        required: false
        type: boolean
        default: true
      run-lint:
        description: "Whether to run linting"
        required: false
        type: boolean
        default: true
      upload-coverage:
        description: "Whether to upload test coverage"
        required: false
        type: boolean
        default: false
    secrets:
      CODECOV_TOKEN:
        description: "Codecov token for coverage upload"
        required: false

jobs:
  test:
    if: inputs.run-tests
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go Environment
        uses: ./.github/actions/setup-go
        with:
          go-version: ${{ inputs.go-version }}

      - name: Run tests
        run: go test -v -race -coverprofile=coverage.out ./...

      - name: Upload coverage to Codecov
        if: inputs.upload-coverage
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.out
          flags: unittests
          name: codecov-umbrella

  lint:
    if: inputs.run-lint
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go Environment
        uses: ./.github/actions/setup-go
        with:
          go-version: ${{ inputs.go-version }}

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: --timeout=5m
