name: Docker Build

on:
  workflow_dispatch:
    inputs:
      push:
        description: "Trigger a release build and push Docker images"
        required: true
        default: false
        type: boolean
  push:
    branches: [master]
    tags: ["v*"]
  pull_request:
    branches: [master]

jobs:
  docker:
    name: Build and Push Docker Images
    uses: ./.github/workflows/docker-build.yml
    with:
      push: ${{ inputs.push || github.event_name != 'pull_request' }}
      go-version: "1.24"
      alpine-version: "3.22"
      generate-sbom: ${{ github.event_name != 'pull_request' }}
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
