name: Package Cleanup
on:
  workflow_dispatch:
jobs:
  ghcr_cleanup:
    name: ghcr.io cleanup action
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: dataaxiom/ghcr-cleanup-action@v1.0.9
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          dry-run: true
          delete-untagged: true
